#!/bin/bash

create_variable_name () { 
  echo $1 | sed -e 's/-/ /g' -e 's/\b\(.\)/\u\1/g' -e 's/ //g'
}

COMPONENT_VARIABLE_NAME=$(create_variable_name $1)

mkdir $1
cd $1

printf "import React from 'react';\nimport * as S from './style';\n\nconst ${COMPONENT_VARIABLE_NAME} = () => {\n\treturn (\n\t\t<div>\n\t\t\t<p>Your new component.</p>\n\t\t</div>\n\t);\n};\n\nexport default ${COMPONENT_VARIABLE_NAME};\n" >> index.jsx

printf "import styled from 'styled-components';\n" >> style.js

echo "New React styled-component - ${1} - has been scaffolded!"
