#!/bin/bash

generate_file_name() {
  echo $1.$2
}

TEMPLATENAME=template
TEMPLATELANG=html
TEMPLATEFILE=$(generate_file_name $TEMPLATENAME $TEMPLATELANG)

STYLENAME=style
STYLELANG=scss
STYLEFILE=$(generate_file_name $STYLENAME $STYLELANG)

SCRIPTNAME=script
SCRIPTLANG=js
SCRIPTFILE=$(generate_file_name $SCRIPTNAME $SCRIPTLANG)

mkdir $1
cd $1
touch $TEMPLATEFILE $STYLEFILE

printf "<template src=\"./${TEMPLATEFILE}\" />\n<style src=\"./${STYLEFILE}\" lang=\"${STYLELANG}\" scoped />\n<script src=\"./${SCRIPTNAME}\" />\n" >>index.vue

printf "export default {};\n" >>${SCRIPTFILE}

echo "New split Vue component - ${1} - has been scaffolded"
